# Generated by Django 3.1.7 on 2021-04-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_review_like_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='reviews', to='community.Hashtag'),
        ),
    ]
