# Generated by Django 3.1.7 on 2021-04-06 16:15

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20210402_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default=1, upload_to='article_images/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
