# Generated by Django 3.1.7 on 2021-04-19 15:38

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='article_images/%Y/%m/%d/'),
        ),
    ]
